version: "3"

services:
    muskalla:
        container_name: muskalla
        image: nginx
        restart: unless_stopped
        ports:
            - "127.0.0.1:<REDACTED>:80"
        environment:
            - TZ=Europe/Berlin
            - HOST_NAME=muskalla.saarland
        volumes:
            - /<REDACTED>/muskalla/html/:/usr/share/nginx/html
            - /<REDACTED>/muskalla/conf.d/:/etc/nginx/conf.d
